# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-19 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='author',
            field=models.CharField(blank=True, db_column='author', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='comments',
            field=models.CharField(blank=True, db_column='comments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='date',
            field=models.CharField(blank=True, db_column='date', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='price',
            field=models.CharField(blank=True, db_column='price', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='publisher',
            field=models.CharField(blank=True, db_column='publisher', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='rate',
            field=models.CharField(blank=True, db_column='rate', max_length=100, null=True),
        ),
    ]
