# Generated by Django 2.2 on 2019-04-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190419_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
