# Generated by Django 2.2 on 2019-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='jingdong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='title', max_length=100, null=True)),
                ('price', models.CharField(blank=True, db_column='price', max_length=100, null=True)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=100, null=True)),
            ],
        ),
    ]
